const test=require("node:test"),assert=require("node:assert/strict"),fs=require("node:fs"),os=require("node:os"),path=require("node:path"),crypto=require("node:crypto");
const {spawnSync}=require("node:child_process");const {writeInstalledReleaseManifest,verifyInstalledReleaseManifest}=require("./installed-release-manifest.cjs");
const {BACKEND_READY_TIMEOUT_MS,CDP_PORT,COUNTERS,DIAGNOSTIC_COUNTERS,SNAPSHOT,STOP_TIMEOUT_MS,activeMeetings,controlledLaunchArgs,deltas,dispatchFormalInput,finishTransition,firstBreak,firstFrameDecision,generationRequestState,inputAction,inputPoint,inputProof,inspectOpenMeetingDb,markSessionReadinessBoundary,physical,prepareTrustedStart,primaryFirstBreak,productPages,readiness,recordStartNetworkEvent,recordTransition,releaseManifest,rendererSessionReadinessExpression,report,resolveInstalledBundle,resolveOpenMeetingDb,run,safeResponseStatus,sessionNetworkRecovered,settleStartedMeeting,snapshot,startNetworkAggregate,startNetworkReport,stopComplete,stopPlan,transitionAggregate,waitForManualStartSettlement,waitForMeetingDb,waitForRendererReady,waitForSessionReadiness,withControlledApp,writeReport}=require("./core-e2e-acceptance.cjs");
const s=(n=1,over={})=>Object.assign({main_tcc:"granted",renderer_permission:"granted",capture_state:"capturing",app_track_live:true,audio_context_state:"running",explicit_fake:false},Object.fromEntries(COUNTERS.map(k=>[k,k==="dropped"?0:n])),over);
const diagnostic=(n=0,over={})=>Object.assign({transport_ready:true,queue_depth:n,global_queue_depth:n+1,staging_items:n+2,staging_bytes:n+3,recovering:false,quarantined_foreign_fence_items:n+4,expired_items:n,consecutive_failures:n+5,last_http_status:200,transport_last_error_code:null,active_in_flight_current:n+6,active_in_flight_max:n, recovery_in_flight_current:n+7,recovery_in_flight_max:n,global_in_flight_current:n+8,global_in_flight_max:n,attempt_count:n,acknowledged_count:n,completed_request_count:n,last_enqueue_reject_reason:null,active_partition_item_count:n+9,active_partition_byte_count:n+10,active_partition_max_items:n+11,active_partition_max_bytes:n+12,global_item_count:n+13,global_byte_count:n+14,global_max_items:n+15,global_max_bytes:n+16,partition_count:n+17},over);
const processReport=(over={})=>Object.assign({logical_backend_count:0,supervisor_count:0,runtime_child_count:0,listener_count:0,process_tree_pid_count:0,backend_pid_count:0,backend_pid_count_deprecated_bool:true},over);
function assertDeepReportPrivacy(value){const visit=(candidate)=>{if(candidate===null||candidate===undefined)return;if(Array.isArray(candidate)){candidate.forEach(visit);return;}if(typeof candidate==="object"){for(const [key,nested] of Object.entries(candidate)){assert.doesNotMatch(key,/(^|_)(id|key|url|content|payload|credential|token|cookie|header|body|path)($|_)/i);visit(nested);}return;}if(typeof candidate==="string")assert.doesNotMatch(candidate,/(^|[_.:\/-])(id|key|url|content|payload|credential|token|cookie|header|body|path)([_.:\/-]|$)/i);};visit(value);}
test("success report is written once",()=>{const p=path.join(os.tmpdir(),`core-${process.pid}.json`);writeReport(report("complete",{pre:s(0),first:s(1),post:s(2),deltas:deltas(s(1),s(2))}),p);assert.equal(JSON.parse(fs.readFileSync(p)).schema,"echodesk-core-e2e-v2");});
test("permission fake and first-frame timeout classify safely",()=>{assert.equal(physical(s(1,{renderer_permission:"denied"})),false);assert.equal(physical(s(1,{explicit_fake:true})),false);assert.equal(report("first_frame",{first_break:"frames"}).first_break,"frames");});
test("transport zero and exception retain one schema",()=>{const d=deltas(s(1),s(2,{ack:1}));assert.equal(firstBreak(d),"ack");assert.equal(report("window",{error_code:"exception"}).error_code,"exception");});
test("safe transport diagnostics keep gauges absolute and monotonic counters as deltas",()=>{const before=snapshot({...s(10),...diagnostic(10)}),after=snapshot({...s(12),...diagnostic(13,{queue_depth:4,recovering:true,active_in_flight_current:2})}),delta=deltas(before,after);assert.equal(after.queue_depth,4);assert.equal(after.recovering,true);assert.equal(after.active_in_flight_current,2);assert.equal(Object.hasOwn(delta,"queue_depth"),false);for(const key of DIAGNOSTIC_COUNTERS)assert.equal(delta[key],3);});
test("missing optional transport diagnostics stay null or unknown for the current installed schema",()=>{const value=snapshot(s(1));for(const key of ["queue_depth","global_queue_depth","staging_items","staging_bytes","quarantined_foreign_fence_items","expired_items","consecutive_failures","active_in_flight_current","active_in_flight_max","recovery_in_flight_current","recovery_in_flight_max","global_in_flight_current","global_in_flight_max","attempt_count","acknowledged_count","completed_request_count","active_partition_item_count","active_partition_byte_count","active_partition_max_items","active_partition_max_bytes","global_item_count","global_byte_count","global_max_items","global_max_bytes","partition_count"])assert.equal(value[key],null);assert.equal(value.recovering,null);assert.equal(value.last_http_status,null);assert.equal(value.transport_last_error_code,"unknown");assert.equal(value.last_enqueue_reject_reason,"unknown");});
test("renderer diagnostics projection reads only the approved product aggregates once",()=>{for(const field of ["lastEnqueueRejectReason","activePartitionItemCount","activePartitionByteCount","activePartitionMaxItems","activePartitionMaxBytes","globalItemCount","globalByteCount","globalMaxItems","globalMaxBytes","partitionCount"])assert.equal(SNAPSHOT.split(`\"${field}\"`).length-1,1);const value=snapshot({...s(1),...diagnostic(1),partition_key:"forbidden",item_id:"forbidden",payload:"forbidden",credential:"forbidden"});assert.equal(Object.keys(value).some((key)=>/[A-Z]/.test(key)),false);assert.equal("partition_key" in value,false);assert.equal("item_id" in value,false);assert.equal("payload" in value,false);assert.equal("credential" in value,false);assertDeepReportPrivacy(report("window",{pre:value,first:value,post:value,deltas:deltas(value,value)}));});
test("transport readiness is optional and projected once without widening privacy",()=>{assert.equal(SNAPSHOT.split('"transportReady"').length-1,1);assert.equal(snapshot(s(1)).transport_ready,null);const value=snapshot({...s(1),...diagnostic(1)});assert.equal(value.transport_ready,true);assert.equal(report("window",{post:value}).transport_ready,true);assertDeepReportPrivacy(report("window",{post:value}));});
test("durable admission accepts active partition growth when renderer enqueue counter stays zero",()=>{const before=snapshot({...s(1),...diagnostic(1,{active_partition_item_count:2,enqueued:7})}),after=snapshot({...s(2),...diagnostic(2,{active_partition_item_count:5,enqueued:7})}),delta=deltas(before,after),value=report("window",{pre:before,post:after,deltas:delta});assert.equal(delta.durable_admission_delta,3);assert.equal(delta.durable_admission_source,"active_partition_items");assert.notEqual(firstBreak(delta),"enqueued");assert.equal(value.durable_admission_delta,3);assert.equal(value.durable_admission_source,"active_partition_items");});
test("durable admission fails enqueued when counter and active partition growth are both zero",()=>{const before=snapshot({...s(1),...diagnostic(1,{active_partition_item_count:2,enqueued:7})}),after=snapshot({...s(2),...diagnostic(2,{active_partition_item_count:2,enqueued:7})}),delta=deltas(before,after);assert.equal(delta.durable_admission_delta,0);assert.equal(firstBreak(delta),"enqueued");});
test("durable admission keeps acknowledged dequeue on the renderer counter path",()=>{const before=snapshot({...s(1),...diagnostic(1,{active_partition_item_count:4,enqueued:7})}),after=snapshot({...s(2),...diagnostic(2,{active_partition_item_count:0,enqueued:8})}),delta=deltas(before,after);assert.equal(delta.durable_admission_delta,1);assert.equal(delta.durable_admission_source,"enqueued_counter");assert.notEqual(firstBreak(delta),"enqueued");assertDeepReportPrivacy(report("window",{pre:before,post:after,deltas:delta}));});
test("legacy diagnostics without active item count use only the enqueue counter",()=>{const before=snapshot(s(1,{enqueued:7})),after=snapshot(s(2,{enqueued:8})),delta=deltas(before,after);assert.equal(delta.durable_admission_delta,1);assert.equal(delta.durable_admission_source,"legacy_enqueued_counter");assert.notEqual(firstBreak(delta),"enqueued");});
test("primary counter code wins over a stop phase when classifying the first break",()=>{assert.equal(primaryFirstBreak("enqueued","stop_settle"),"enqueued");});
test("stop does not dispatch when database is already stopped",()=>{assert.deepEqual(stopPlan(0),{state:"none",action:"already_stopped",visible_bool:null});assert.deepEqual(stopComplete(0,0,null),{state:"none",action:"already_stopped",visible_bool:null});});
test("active meeting stop reports input dispatch rather than DOM click",()=>{assert.deepEqual(stopPlan(1),{state:"in_meeting",action:"input_dispatch",visible_bool:null});assert.deepEqual(stopComplete(1,0,{action:"input_dispatch",visible_bool:true}),{state:"none",action:"input_dispatch",visible_bool:true});});
test("active meeting fails when formal target is hidden",()=>{assert.throws(()=>stopComplete(1,1,{action:"input_dispatch",visible_bool:false}),/toggle_stop_target/);});
test("active meeting fails when persisted state remains in progress",()=>{assert.throws(()=>stopComplete(1,1,{action:"input_dispatch",visible_bool:true}),/toggle_stop_persisted/);});
test("installed stop timeout covers renderer quiesce and backend receipt settlement",()=>{assert.equal(STOP_TIMEOUT_MS,300_000);});
test("frozen backend readiness has an independent startup budget",()=>{assert.equal(BACKEND_READY_TIMEOUT_MS,45_000);});
test("input dispatch brings page front then emits moved press release and reports trusted proof counts only",async()=>{const calls=[],values=[true,{visible_bool:true,x:12,y:34},{click_event_count:1,trusted_event_count:1}];const action=await dispatchFormalInput({evaluate:async()=>values.shift(),command:async(method,params={})=>calls.push({method,params})});assert.deepEqual(action,{action:"input_dispatch",visible_bool:true,click_event_count:1,trusted_event_count:1});assert.deepEqual(calls,[{method:"Page.bringToFront",params:{}},{method:"Input.dispatchMouseEvent",params:{type:"mouseMoved",button:"none",buttons:0,x:12,y:34}},{method:"Input.dispatchMouseEvent",params:{type:"mousePressed",button:"left",buttons:1,clickCount:1,x:12,y:34}},{method:"Input.dispatchMouseEvent",params:{type:"mouseReleased",button:"left",buttons:0,clickCount:1,x:12,y:34}}]);const safe=report("toggle_start",{start:action});assert.deepEqual(safe.start,{action:"input_dispatch",visible_bool:true,click_event_count:1,trusted_event_count:1});assert.doesNotMatch(JSON.stringify(safe.start),/"x"|"y"|url|header|body|payload|credential|target|text/i);});
test("input proof distinguishes no delivered click from a trusted delivered click",()=>{assert.deepEqual(inputAction(true,{click_event_count:0,trusted_event_count:0}),{action:"input_dispatch",visible_bool:true,click_event_count:0,trusted_event_count:0});assert.deepEqual(inputProof({click_event_count:1,trusted_event_count:1}),{click_event_count:1,trusted_event_count:1});assert.throws(()=>inputProof({click_event_count:0,trusted_event_count:1}),/input_proof/);});
test("input dispatch rejects hidden or zero rectangles before mouse input",async()=>{for(const target of [{visible_bool:false},{visible_bool:true,x:0,y:0}]){let sent=0;const values=[true,target];await assert.rejects(()=>dispatchFormalInput({evaluate:async()=>values.shift(),command:async()=>{sent+=1;}}),/toggle_input_target/);assert.equal(sent,1);}assert.equal(inputPoint({visible_bool:true,x:0,y:0}),null);});
test("runner production source has no DOM click invocation",()=>{assert.equal(fs.readFileSync(path.join(__dirname,"core-e2e-acceptance.cjs"),"utf8").includes(".click("),false);});
const lifecycle=(over={})=>{const calls=[];const runtime=Object.assign({quitStandardApp:async()=>calls.push("quit"),assertPortAvailable:async(port)=>calls.push(`port:${port}`),launch:(exe,args)=>{calls.push({exe,args});return {pid:731,exitCode:null,signalCode:null,kill:()=>{}};},waitForCdp:async(endpoint)=>calls.push(`ready:${endpoint}`),stopControlled:async()=>calls.push("stop"),restoreStandardApp:async()=>calls.push("restore")},over);return {calls,runtime};};
test("controlled lifecycle spawns current app with only the CDP port argument",async()=>{const {calls,runtime}=lifecycle();const value=await withControlledApp({app:"/Applications/EchoDesk.app",runtime},async()=>"ok");assert.equal(value,"ok");assert.deepEqual(controlledLaunchArgs(),[`--remote-debugging-port=${CDP_PORT}`]);assert.deepEqual(calls[2],{exe:"/Applications/EchoDesk.app/Contents/MacOS/EchoDesk",args:[`--remote-debugging-port=${CDP_PORT}`]});assert.deepEqual(calls.slice(-2),["stop","restore"]);});
test("CDP timeout always stops controlled app and restores standard app",async()=>{const {calls,runtime}=lifecycle({waitForCdp:async()=>{throw new Error("cdp_timeout");}});await assert.rejects(()=>withControlledApp({app:"/Applications/EchoDesk.app",runtime},async()=>{}),/cdp_timeout/);assert.deepEqual(calls.slice(-2),["stop","restore"]);});
test("successful lifecycle always restores standard app",async()=>{const {calls,runtime}=lifecycle();await withControlledApp({app:"/Applications/EchoDesk.app",runtime},async()=>{});assert.equal(calls.at(-1),"restore");});
test("existing CDP port is never connected or reused",async()=>{let launched=false,waited=false;const {calls,runtime}=lifecycle({assertPortAvailable:async()=>{throw new Error("cdp_port_in_use");},launch:()=>{launched=true;},waitForCdp:async()=>{waited=true;}});await assert.rejects(()=>withControlledApp({app:"/Applications/EchoDesk.app",runtime},async()=>{}),/cdp_port_in_use/);assert.equal(launched,false);assert.equal(waited,false);assert.equal(calls.at(-1),"restore");});
test("renderer readiness waits for delayed product diagnostics",async()=>{let listed=0,inspected=0;const dev={type:"page",url:"devtools://devtools",webSocketDebuggerUrl:"ws://dev"},product={type:"page",url:"app://echodesk",webSocketDebuggerUrl:"ws://product"};const connection={socket:{close:()=>{}}};const result=await waitForRendererReady("http://127.0.0.1:9335",{listTargets:async()=>++listed===1?[dev]:[dev,product],inspectProductTarget:async()=>({connection,ready_bool:++inspected>1,diagnostics_bool:inspected>1}),delay:async()=>{},timeout:1000});assert.equal(result.connection,connection);assert.deepEqual(result.readiness,readiness(1,true,true,3));});
test("renderer readiness timeout writes one safe report",async()=>{const root=fs.mkdtempSync(path.join(os.tmpdir(),"core-ready-")),app=path.join(root,"EchoDesk.app"),exe=path.join(app,"Contents","MacOS","EchoDesk"),reportPath=path.join(root,"report.json");fs.mkdirSync(path.dirname(exe),{recursive:true});fs.writeFileSync(exe,"x");const sha=crypto.createHash("sha256").update("x").digest("hex");const {runtime}=lifecycle({waitForRendererReady:async()=>{const error=new Error("renderer_ready_timeout");error.code="renderer_ready_timeout";error.readiness=readiness(0,false,false,3);throw error;}});const result=await run({app,sha256:sha,db:path.join(root,"missing.db"),report:reportPath,runtime});assert.equal(result.error_code,"renderer_ready_timeout");assert.deepEqual(result.readiness,readiness(0,false,false,3));assert.deepEqual(Object.keys(JSON.parse(fs.readFileSync(reportPath))).sort(),Object.keys(result).sort());});
test("product target selection excludes devtools pages",()=>{assert.deepEqual(productPages([{type:"page",url:"devtools://devtools",webSocketDebuggerUrl:"ws://dev"},{type:"page",url:"app://echodesk",webSocketDebuggerUrl:"ws://product"}]).map((target)=>target.webSocketDebuggerUrl),["ws://product"]);});
test("initializing to capturing frame records only complete transition aggregates",()=>{const transition=transitionAggregate(0),control={disabled:false,aria_pressed:false};recordTransition(transition,s(0,{capture_state:"initializing",app_track_live:false,audio_context_state:"none",last_error_code:"none"}),0,control);const live=s(1,{capture_state:"capturing",last_error_code:"none"});recordTransition(transition,live,1,{disabled:true,aria_pressed:true});const safe=finishTransition(transition);assert.deepEqual(Object.keys(safe).sort(),["ariaPressedCounts","audioContextCounts","buttonDisabledCounts","captureStateCounts","durationMs","inMeetingCounts","lastErrorCodeCounts","pollTotal","trackLiveCounts"].sort());assert.equal(safe.pollTotal,2);assert.equal(firstFrameDecision(s(0),live),"ready");});
test("sustained initializing remains pending and report writes one transition object",()=>{const transition=transitionAggregate(0),initial=s(0,{capture_state:"initializing",app_track_live:false,audio_context_state:"none",last_error_code:"none"});recordTransition(transition,initial,0,{disabled:false,aria_pressed:false});assert.equal(firstFrameDecision(s(0),initial),"pending");assert.deepEqual(report("first_frame",{transition:finishTransition(transition)}).transition.captureStateCounts,{initializing:1});});
test("rejected machine error is classified before frame timeout",()=>{assert.equal(firstFrameDecision(s(0),s(0,{last_error_code:"capture_rejected"})),"capture_rejected");});
const manualStart=(requestId="start-1")=>({method:"Network.requestWillBeSent",params:{requestId,request:{method:"POST",url:"https://private.invalid/meetings/manual_start?credential=redacted"}}});
const sessionBootstrap=(requestId="session-1")=>({method:"Network.requestWillBeSent",params:{requestId,request:{method:"GET",url:"https://private.invalid/bootstrap?credential=redacted"}}});
const networkResponse=(requestId,status)=>({method:"Network.responseReceived",params:{requestId,response:{status,url:"https://private.invalid/secret",headers:{authorization:"secret"}}}});
const networkFinished=(requestId)=>({method:"Network.loadingFinished",params:{requestId}});
test("network diagnostic reports no request as empty aggregate only",()=>{const network=startNetworkAggregate();recordStartNetworkEvent(network,networkResponse("untracked",200));const value=startNetworkReport(network,transitionAggregate(0));assert.deepEqual(value,{start_request_count:0,response_status_counts:{},network_error_class_counts:{},session_request_count:0,session_status_counts:{},session_error_class_counts:{},state_transition:{in_meeting_0:0,in_meeting_1:0}});});
test("bootstrap 2xx opens one start generation whose manual request must settle",()=>{const network=startNetworkAggregate();recordStartNetworkEvent(network,sessionBootstrap());recordStartNetworkEvent(network,networkResponse("session-1",200));assert.equal(sessionNetworkRecovered(network),true);const generation=markSessionReadinessBoundary(network);recordStartNetworkEvent(network,manualStart());recordStartNetworkEvent(network,networkResponse("start-1",204));recordStartNetworkEvent(network,networkFinished("start-1"));assert.deepEqual(generationRequestState(network,"manual",generation),{request_count:1,pending_count:0,http_2xx_count:1,http_failure_count:0,network_failure_count:0});assert.deepEqual(startNetworkReport(network,{inMeetingCounts:{"0":1,"1":2}}),{start_request_count:1,response_status_counts:{"204":1},network_error_class_counts:{},session_request_count:1,session_status_counts:{"200":1},session_error_class_counts:{},state_transition:{in_meeting_0:1,in_meeting_1:2}});});
test("bootstrap non2xx cannot satisfy session readiness",async()=>{const network=startNetworkAggregate();recordStartNetworkEvent(network,sessionBootstrap());recordStartNetworkEvent(network,networkResponse("session-1",503));await assert.rejects(()=>waitForSessionReadiness({},network,{waitForRendererSession:async()=>({backend_2xx_bool:true,renderer_backend_ready_bool:true,renderer_session_ready_bool:true})}),/session_readiness/);});
test("bootstrap loadingFailed remains a bounded readiness failure class",async()=>{const network=startNetworkAggregate();recordStartNetworkEvent(network,sessionBootstrap());recordStartNetworkEvent(network,{method:"Network.loadingFailed",params:{requestId:"session-1",errorText:"net::ERR_CONNECTION_REFUSED https://private.invalid/token"}});await assert.rejects(()=>waitForSessionReadiness({},network,{waitForRendererSession:async()=>({backend_2xx_bool:false,renderer_backend_ready_bool:false,renderer_session_ready_bool:false})}),/session_readiness/);assert.deepEqual(startNetworkReport(network,transitionAggregate(0)).session_error_class_counts,{connection:1});});
test("missing bootstrap evidence cannot advance to a start transaction",async()=>{const network=startNetworkAggregate();await assert.rejects(()=>waitForSessionReadiness({},network,{waitForRendererSession:async()=>({backend_2xx_bool:true,renderer_backend_ready_bool:true,renderer_session_ready_bool:true})}),/session_readiness/);assert.equal(network.manualTransaction,null);});
test("network diagnostic records manual-start 2xx status without request metadata",()=>{const network=startNetworkAggregate();recordStartNetworkEvent(network,manualStart());recordStartNetworkEvent(network,networkResponse("start-1",204));assert.deepEqual(startNetworkReport(network,{inMeetingCounts:{"0":1,"1":2}}).response_status_counts,{"204":1});});
test("network diagnostic records manual-start non2xx status without request metadata",()=>{const network=startNetworkAggregate();recordStartNetworkEvent(network,manualStart());recordStartNetworkEvent(network,{method:"Network.responseReceived",params:{requestId:"start-1",response:{status:503,headers:{authorization:"secret"}}}});assert.deepEqual(startNetworkReport(network,transitionAggregate(0)).response_status_counts,{"503":1});assert.equal(safeResponseStatus(600),null);});
test("network diagnostic records loadingFailed as a bounded class without URL header body or payload",()=>{const network=startNetworkAggregate();recordStartNetworkEvent(network,manualStart());recordStartNetworkEvent(network,{method:"Network.loadingFailed",params:{requestId:"start-1",errorText:"net::ERR_CONNECTION_REFUSED https://private.invalid/token",blockedReason:"",body:"private body",headers:{cookie:"private"},payload:"private"}});const value=report("first_frame",{start_network:startNetworkReport(network,transitionAggregate(0))});assert.deepEqual(value.start_network.network_error_class_counts,{connection:1});assert.deepEqual(Object.keys(value.start_network).sort(),["network_error_class_counts","response_status_counts","session_error_class_counts","session_request_count","session_status_counts","start_request_count","state_transition"]);assert.doesNotMatch(JSON.stringify(value.start_network),/private|url|path|header|body|payload|credential|token|cookie/i);});
test("manual 2xx without persisted meeting fails manual_start_state",async()=>{const network=startNetworkAggregate();markSessionReadinessBoundary(network);recordStartNetworkEvent(network,manualStart());recordStartNetworkEvent(network,networkResponse("start-1",204));recordStartNetworkEvent(network,networkFinished("start-1"));let clock=0;await assert.rejects(()=>waitForManualStartSettlement({},"private.db",network,{now:()=>clock,timeout:2,waitForCondition:async()=>{clock+=1;},readActive:()=>0}),(error)=>error.code==="manual_start_state");});
test("session and manual report schema never serializes request metadata",()=>{const network=startNetworkAggregate();recordStartNetworkEvent(network,sessionBootstrap());recordStartNetworkEvent(network,networkResponse("session-1",200));recordStartNetworkEvent(network,manualStart());recordStartNetworkEvent(network,networkResponse("start-1",204));const safe=startNetworkReport(network,transitionAggregate(0));assert.deepEqual(Object.keys(safe).sort(),["network_error_class_counts","response_status_counts","session_error_class_counts","session_request_count","session_status_counts","start_request_count","state_transition"]);assert.doesNotMatch(JSON.stringify(safe),/private|url|path|header|body|payload|credential|token|cookie/i);});
test("session readiness accepts a delayed backend only after the final bootstrap 2xx",async()=>{const network=startNetworkAggregate();let release;const rendererReady=new Promise((resolve)=>{release=resolve;});let settled=false;const waiting=waitForSessionReadiness({},network,{waitForRendererSession:()=>rendererReady}).then((value)=>{settled=true;return value;});assert.equal(settled,false);recordStartNetworkEvent(network,sessionBootstrap("boot-failed"));recordStartNetworkEvent(network,{method:"Network.loadingFailed",params:{requestId:"boot-failed",errorText:"connection refused"}});assert.equal(sessionNetworkRecovered(network),false);recordStartNetworkEvent(network,sessionBootstrap("boot-ready"));recordStartNetworkEvent(network,networkResponse("boot-ready",200));release({backend_2xx_bool:true,renderer_backend_ready_bool:true,renderer_session_ready_bool:true});assert.deepEqual(await waiting,{backend_2xx_bool:true,renderer_backend_ready_bool:true,renderer_session_ready_bool:true});});
test("session readiness timeout fails with the unique session_readiness first break",async()=>{const network=startNetworkAggregate();await assert.rejects(()=>waitForSessionReadiness({},network,{waitForRendererSession:async()=>({backend_2xx_bool:false,renderer_backend_ready_bool:false,renderer_session_ready_bool:false})}),(error)=>error.code==="session_readiness"&&error.session_readiness.backend_2xx_bool===false);assert.equal(report("session_readiness",{error_code:"session_readiness",first_break:"session_readiness"}).first_break,"session_readiness");});
test("old-generation session request late failure is isolated from the start generation",async()=>{const network=startNetworkAggregate();recordStartNetworkEvent(network,sessionBootstrap("old-pending"));recordStartNetworkEvent(network,sessionBootstrap("boot-ready"));recordStartNetworkEvent(network,networkResponse("boot-ready",200));await waitForSessionReadiness({},network,{waitForRendererSession:async()=>({backend_2xx_bool:true,renderer_backend_ready_bool:true,renderer_session_ready_bool:true})});const generation=markSessionReadinessBoundary(network);recordStartNetworkEvent(network,{method:"Network.loadingFailed",params:{requestId:"old-pending",errorText:"connection refused"}});assert.deepEqual(generationRequestState(network,"session",generation),{request_count:0,pending_count:0,http_2xx_count:0,http_failure_count:0,network_failure_count:0});assert.deepEqual(startNetworkReport(network,transitionAggregate(0)).session_error_class_counts,{connection:1});});
test("request_generation_and_settlement_race",async()=>{
  const startNetwork=startNetworkAggregate();
  recordStartNetworkEvent(startNetwork,manualStart("pre-readiness"));
  const transactionGeneration=markSessionReadinessBoundary(startNetwork);
  recordStartNetworkEvent(startNetwork,manualStart("clicked-start"));
  recordStartNetworkEvent(startNetwork,{method:"Network.loadingFailed",params:{requestId:"pre-readiness",errorText:"connection refused"}});
  assert.deepEqual(generationRequestState(startNetwork,"manual",transactionGeneration),{request_count:1,pending_count:1,http_2xx_count:0,http_failure_count:0,network_failure_count:0});

  let startClock=0,startStep=0,startActive=0;
  const startSettlement=await waitForManualStartSettlement({},"private.db",startNetwork,{
    now:()=>startClock,
    timeout:5,
    readActive:()=>startActive,
    waitForCondition:async()=>{
      startClock+=1;
      startStep+=1;
      if(startStep===1){recordStartNetworkEvent(startNetwork,networkResponse("clicked-start",204));recordStartNetworkEvent(startNetwork,networkFinished("clicked-start"));}
      if(startStep===2)startActive=1;
    },
  });
  assert.equal(startStep,2);
  assert.deepEqual(startSettlement,{request_count:1,pending_count:0,http_2xx_count:1,http_failure_count:0,network_failure_count:0,in_meeting_count:1});

  const invalidActiveNetwork=startNetworkAggregate();
  markSessionReadinessBoundary(invalidActiveNetwork);
  recordStartNetworkEvent(invalidActiveNetwork,manualStart("invalid-active"));
  recordStartNetworkEvent(invalidActiveNetwork,networkResponse("invalid-active",204));
  recordStartNetworkEvent(invalidActiveNetwork,networkFinished("invalid-active"));
  let invalidClock=0;
  await assert.rejects(()=>waitForManualStartSettlement({},"private.db",invalidActiveNetwork,{now:()=>invalidClock,timeout:1,readActive:()=>2,waitForCondition:async()=>{invalidClock+=1;}}),(error)=>error.code==="manual_start_state");

  const cleanupNetwork=startNetworkAggregate();
  markSessionReadinessBoundary(cleanupNetwork);
  recordStartNetworkEvent(cleanupNetwork,manualStart("cleanup-start"));
  let cleanupClock=0,cleanupActive=0,stopCount=0;
  const {calls,runtime}=lifecycle();
  await withControlledApp({app:"/Applications/EchoDesk.app",runtime},async()=>{
    const cleanup=await settleStartedMeeting({},"private.db",cleanupNetwork,{
      startOptions:{
        now:()=>cleanupClock,
        timeout:5,
        waitForCondition:async()=>{
          cleanupClock+=1;
          recordStartNetworkEvent(cleanupNetwork,networkResponse("cleanup-start",204));
          recordStartNetworkEvent(cleanupNetwork,networkFinished("cleanup-start"));
          cleanupActive=1;
        },
      },
      readActive:()=>cleanupActive,
      stopActive:async()=>{
        stopCount+=1;
        assert.equal(cleanupActive,1);
        cleanupActive=0;
        calls.push("trusted-stop");
        return {state:"none",...inputAction(true,{click_event_count:1,trusted_event_count:1})};
      },
    });
    assert.equal(cleanup.pending_count,0);
    assert.equal(cleanup.active_count,0);
    assert.equal(cleanup.stop.trusted_event_count,1);
    calls.push("settled-zero");
  });
  assert.equal(stopCount,1);
  assert.ok(calls.indexOf("trusted-stop")<calls.indexOf("settled-zero"));
  assert.ok(calls.indexOf("settled-zero")<calls.indexOf("restore"));
});
test("delayed manual 2xx and in_meeting state settle before first frame",async()=>{const network=startNetworkAggregate();markSessionReadinessBoundary(network);recordStartNetworkEvent(network,manualStart());let clock=0,step=0,active=0;const value=await waitForManualStartSettlement({},"private.db",network,{now:()=>clock,timeout:10,readActive:()=>active,waitForCondition:async()=>{clock+=1;step+=1;if(step===1){recordStartNetworkEvent(network,networkResponse("start-1",204));recordStartNetworkEvent(network,networkFinished("start-1"));}if(step===2)active=1;}});assert.deepEqual(value,{request_count:1,pending_count:0,http_2xx_count:1,http_failure_count:0,network_failure_count:0,in_meeting_count:1});});
test("response-before-observer settles the canonical transaction once",async()=>{const network=startNetworkAggregate();markSessionReadinessBoundary(network);recordStartNetworkEvent(network,manualStart());recordStartNetworkEvent(network,networkResponse("start-1",200));recordStartNetworkEvent(network,networkFinished("start-1"));const value=await waitForManualStartSettlement({},"private.db",network,{readActive:()=>1});assert.deepEqual(value,{request_count:1,pending_count:0,http_2xx_count:1,http_failure_count:0,network_failure_count:0,in_meeting_count:1});});
test("observer-before-response waits without renderer evaluation and then settles",async()=>{const network=startNetworkAggregate();markSessionReadinessBoundary(network);recordStartNetworkEvent(network,manualStart());let clock=0,waits=0;const value=await waitForManualStartSettlement({},"private.db",network,{now:()=>clock,timeout:5,readActive:()=>1,waitForCondition:async()=>{clock+=1;waits+=1;recordStartNetworkEvent(network,networkResponse("start-1",200));}});assert.equal(waits,1);assert.equal(value.http_2xx_count,1);assert.equal(value.in_meeting_count,1);});
test("200 response tolerates asynchronous UI state before entering frame phase",async()=>{const network=startNetworkAggregate();markSessionReadinessBoundary(network);recordStartNetworkEvent(network,manualStart());recordStartNetworkEvent(network,networkResponse("start-1",200));let clock=0,active=0,waits=0;const value=await waitForManualStartSettlement({},"private.db",network,{now:()=>clock,timeout:5,readActive:()=>active,waitForCondition:async()=>{clock+=1;waits+=1;if(waits===2)active=1;}});assert.equal(waits,2);assert.equal(value.pending_count,0);assert.equal(value.in_meeting_count,1);});
test("stale generation callback cannot settle the current manual transaction",async()=>{const network=startNetworkAggregate();markSessionReadinessBoundary(network);recordStartNetworkEvent(network,manualStart("old-start"));const currentGeneration=markSessionReadinessBoundary(network);recordStartNetworkEvent(network,manualStart("current-start"));recordStartNetworkEvent(network,networkResponse("old-start",200));assert.deepEqual(generationRequestState(network,"manual",currentGeneration),{request_count:1,pending_count:1,http_2xx_count:0,http_failure_count:0,network_failure_count:0});recordStartNetworkEvent(network,networkResponse("current-start",200));assert.deepEqual(generationRequestState(network,"manual",currentGeneration),{request_count:1,pending_count:0,http_2xx_count:1,http_failure_count:0,network_failure_count:0});});
test("cleanup reuses the canonical transaction after a pending failed start",async()=>{const network=startNetworkAggregate();markSessionReadinessBoundary(network);recordStartNetworkEvent(network,manualStart());let clock=0,waits=0;const value=await settleStartedMeeting({},"private.db",network,{startOptions:{now:()=>clock,timeout:5,waitForCondition:async()=>{clock+=1;waits+=1;recordStartNetworkEvent(network,{method:"Network.loadingFailed",params:{requestId:"start-1",errorText:"connection refused"}});}},readActive:()=>0,stopActive:async()=>{throw new Error("must_not_stop");}});assert.equal(waits,1);assert.equal(value.active_count,0);});
test("finally automatically dispatches the formal stop for a late active meeting",async()=>{const network=startNetworkAggregate();markSessionReadinessBoundary(network);recordStartNetworkEvent(network,manualStart());recordStartNetworkEvent(network,networkResponse("start-1",204));recordStartNetworkEvent(network,networkFinished("start-1"));let active=1,stops=0;const value=await settleStartedMeeting({},"private.db",network,{readActive:()=>active,stopActive:async()=>{stops+=1;active=0;return {state:"none",action:"input_dispatch",visible_bool:true};}});assert.equal(stops,1);assert.equal(value.pending_count,0);assert.equal(value.active_count,0);assert.equal(value.start_settlement.http_2xx_count,1);assert.deepEqual(value.stop,{state:"none",action:"input_dispatch",visible_bool:true});});
test("controlled lifecycle restores only after pending zero and active zero",async()=>{const network=startNetworkAggregate();markSessionReadinessBoundary(network);recordStartNetworkEvent(network,manualStart());recordStartNetworkEvent(network,{method:"Network.loadingFailed",params:{requestId:"start-1",errorText:"connection refused"}});const {calls,runtime}=lifecycle();await withControlledApp({app:"/Applications/EchoDesk.app",runtime},async()=>{calls.push("cleanup-start");await settleStartedMeeting({},"private.db",network,{readActive:()=>0});calls.push("cleanup-complete");});assert.ok(calls.indexOf("cleanup-complete")<calls.indexOf("stop"));assert.ok(calls.indexOf("stop")<calls.indexOf("restore"));});
test("trusted click is strictly sequenced after session readiness and baseline",async()=>{const order=[],network=startNetworkAggregate();const value=await prepareTrustedStart({},network,{waitForReadiness:async()=>{order.push("ready");return {backend_2xx_bool:true,renderer_backend_ready_bool:true,renderer_session_ready_bool:true};},readBaseline:async()=>{order.push("baseline");return s(0);},onBeforeInput:()=>order.push("input-boundary"),dispatchInput:async()=>{order.push("click");return inputAction(true,{click_event_count:1,trusted_event_count:1});}});assert.deepEqual(order,["ready","baseline","input-boundary","click"]);assert.equal(value.start.trusted_event_count,1);});
test("runner happy order is readiness click start-settle frame stop-settle restore",()=>{const source=fs.readFileSync(path.join(__dirname,"core-e2e-acceptance.cjs"),"utf8"),runBlock=source.split("async function run(options)",2)[1].split("async function runInstalled",1)[0],ordered=["prepareTrustedStart","waitForManualStartSettlement","phase=\"first_frame\"","phase=\"stop_settle\"","stopSettlementValue.active_count","post=snapshot(await connection.evaluate(SNAPSHOT))","deltasValue=deltas"].map((token)=>runBlock.indexOf(token));assert.ok(ordered.every((value)=>value>=0));assert.deepEqual([...ordered].sort((a,b)=>a-b),ordered);assert.doesNotMatch(runBlock,/if\(connection&&started\)\{try\{stop=await stopMeeting/);assert.match(runBlock,/settleStartedMeeting/);assert.doesNotMatch(runBlock,/dispatchFormalInput\(connection,["']toggle_start_target["']\)/);assert.match(rendererSessionReadinessExpression(1),/MutationObserver/);assert.doesNotMatch(rendererSessionReadinessExpression(1),/location\.reload|\.reload\(/);});
function installedFixture({hash}={}){const root=fs.mkdtempSync(path.join(os.tmpdir(),"core-installed-")),app=path.join(root,"EchoDesk.app"),exe=path.join(app,"Contents","MacOS","EchoDesk"),renderer=path.join(app,"Contents","Resources","app.asar"),backend=path.join(app,"Contents","Resources","backend","echodesk-backend"),manifest=path.join(root,"installed-release-manifest.json");for(const [file,value] of [[exe,"installed"],[renderer,"renderer"],[backend,"backend"]]){fs.mkdirSync(path.dirname(file),{recursive:true});fs.writeFileSync(file,value);}const hashes=Object.fromEntries([["executable_sha256",exe],["renderer_sha256",renderer],["backend_sha256",backend]].map(([key,file])=>[key,crypto.createHash("sha256").update(fs.readFileSync(file)).digest("hex")]));fs.writeFileSync(manifest,JSON.stringify({version:"0.3.5",build:"0.3.5",...hashes, ...(hash?{executable_sha256:hash}:{})}));return {app,manifest,actual:hashes.executable_sha256,backend};}
async function runPrimaryCleanupContract({cleanupFails=false}={}){const f=installedFixture(),reportPath=path.join(path.dirname(f.manifest),"report.json"),network=startNetworkAggregate(),connection={socket:{close:()=>{}},enableStartNetworkDiagnostics:async()=>network,evaluate:async()=>s(0)};const {calls,runtime}=lifecycle({waitForRendererReady:async()=>({connection,readiness:readiness(1,true,true,1)}),waitForSessionReadiness:async()=>({backend_2xx_bool:true,renderer_backend_ready_bool:true,renderer_session_ready_bool:true}),dispatchFormalInput:async()=>inputAction(true,{click_event_count:1,trusted_event_count:1}),waitForManualStartSettlement:async()=>{const error=new Error("enqueued");error.code="enqueued";throw error;},settleStartedMeeting:async()=>{calls.push("meeting-cleanup");if(cleanupFails){const error=new Error("toggle_stop_persisted");error.code="toggle_stop_persisted";error.stop_settlement={pending_count:0,active_count:1,stop:{state:"in_meeting",...inputAction(true,{click_event_count:1,trusted_event_count:1})}};throw error;}return {pending_count:0,active_count:0,stop:{state:"none",...inputAction(true,{click_event_count:1,trusted_event_count:1})}};}});const result=await run({app:f.app,sha256:f.actual,db:"opaque.db",report:reportPath,runtime});return {calls,result,written:JSON.parse(fs.readFileSync(reportPath,"utf8"))};}
test("response after timeout is retained as final evidence without replacing primary failure",async()=>{const f=installedFixture(),network=startNetworkAggregate(),connection={socket:{close:()=>{}},enableStartNetworkDiagnostics:async()=>network,evaluate:async()=>s(0)},atTimeout={request_count:1,pending_count:1,http_2xx_count:0,http_failure_count:0,network_failure_count:0,in_meeting_count:1},finalValue={request_count:1,pending_count:0,http_2xx_count:1,http_failure_count:0,network_failure_count:0,in_meeting_count:1},{runtime}=lifecycle({waitForRendererReady:async()=>({connection,readiness:readiness(1,true,true,1)}),waitForSessionReadiness:async()=>({backend_2xx_bool:true,renderer_backend_ready_bool:true,renderer_session_ready_bool:true}),dispatchFormalInput:async()=>inputAction(true,{click_event_count:1,trusted_event_count:1}),waitForManualStartSettlement:async()=>{const error=new Error("manual_start_http");error.code="manual_start_http";error.start_settlement=atTimeout;error.start_settlement_timeout=true;throw error;},settleStartedMeeting:async()=>({pending_count:0,active_count:0,start_settlement:finalValue,stop:{state:"none",action:"already_stopped",visible_bool:null}})});const result=await run({app:f.app,sha256:f.actual,db:"opaque.db",runtime});assert.equal(result.phase,"start_settle");assert.equal(result.first_break,"manual_start_http");assert.equal(result.error_code,"manual_start_http");assert.deepEqual(result.start_settlement_at_timeout,atTimeout);assert.deepEqual(result.start_settlement_final,finalValue);assert.equal(result.response_after_timeout,true);});
test("primary enqueued failure survives successful cleanup with pending and active zero",async()=>{const {calls,result,written}=await runPrimaryCleanupContract();assert.equal(result.phase,"start_settle");assert.equal(result.first_break,"enqueued");assert.equal(result.error_code,"enqueued");assert.equal(result.cleanup_phase,"stop_settle");assert.equal(result.cleanup_first_break,null);assert.equal(result.cleanup_error,null);assert.deepEqual(result.stop_settlement,{pending_count:0,active_count:0,stop:{state:"none",action:"input_dispatch",visible_bool:true,click_event_count:1,trusted_event_count:1}});assert.deepEqual(written,result);assert.ok(calls.indexOf("meeting-cleanup")<calls.indexOf("stop"));assert.ok(calls.indexOf("stop")<calls.indexOf("restore"));});
test("real cleanup failure is isolated without replacing the primary enqueued outcome",async()=>{const {result}=await runPrimaryCleanupContract({cleanupFails:true});assert.equal(result.phase,"start_settle");assert.equal(result.first_break,"enqueued");assert.equal(result.error_code,"enqueued");assert.equal(result.cleanup_phase,"stop_settle");assert.equal(result.cleanup_first_break,"stop_settlement");assert.equal(result.cleanup_error,"toggle_stop_persisted");assert.equal(result.stop_settlement.pending_count,0);assert.equal(result.stop_settlement.active_count,1);});
test("controlled lifecycle cleanup cannot replace a work failure and still attempts restore",async()=>{const {calls,runtime}=lifecycle({stopControlled:async()=>{calls.push("stop-failed");const error=new Error("controlled_stop_failed");error.code="controlled_stop_failed";throw error;}});await assert.rejects(()=>withControlledApp({app:"/Applications/EchoDesk.app",runtime},async()=>{const error=new Error("enqueued");error.code="enqueued";throw error;}),(error)=>error.code==="enqueued"&&error.controlled_cleanup.phase==="controlled_stop"&&error.controlled_cleanup.error==="controlled_stop_failed");assert.equal(calls.at(-1),"restore");});
test("zero-argument resolver binds all installed resources to a five-field manifest",()=>{const f=installedFixture();const result=resolveInstalledBundle({appPath:f.app,manifestPath:f.manifest});assert.equal(result.app,f.app);assert.equal(result.sha256,f.actual);assert.deepEqual(Object.keys(releaseManifest(f.manifest)).sort(),["backend_sha256","build","executable_sha256","renderer_sha256","version"]);});
test("manifest hash mismatch fails without leaking either path",()=>{const f=installedFixture({hash:"0".repeat(64)});assert.throws(()=>resolveInstalledBundle({appPath:f.app,manifestPath:f.manifest}),(error)=>error.message==="installed_hash");});
test("open database discovery rejects zero matching meetings schemas without path leakage",()=>{assert.throws(()=>resolveOpenMeetingDb(1,{candidates:["private-a.db"],pragma:()=>({status:0,stdout:""})}),(error)=>error.message==="database_missing");});
test("open database discovery rejects multiple matching meetings schemas without path leakage",()=>{assert.throws(()=>resolveOpenMeetingDb(1,{candidates:["private-a.db","private-b.db"],pragma:()=>({status:0,stdout:"cid|name"})}),(error)=>error.message==="database_ambiguous");});
test("PyInstaller parent and runtime child report one logical backend without gating on tree size",()=>{const value=inspectOpenMeetingDb(900,{candidates:["private.db"],pids:[900,901,902,903],fileOwners:new Map([["private.db",new Set([903])]]),runtimePids:[903],supervisorPids:[902],listenerPids:[903],pragma:()=>({status:0,stdout:"cid|name"})});assert.equal(value.error_code,null);assert.deepEqual(value.database,{candidate_count:1,logical_backend_count:1,supervisor_count:1,runtime_child_count:1,listener_count:1,process_tree_pid_count:4,backend_pid_count:1,backend_pid_count_deprecated_bool:true,ready_bool:true});});
test("an opened meeting database is not runtime-ready before its backend listener binds",()=>{const value=inspectOpenMeetingDb(900,{candidates:["private.db"],pids:[900,901,902,903],fileOwners:new Map([["private.db",new Set([903])]]),runtimePids:[903],supervisorPids:[902],listenerPids:[],pragma:()=>({status:0,stdout:"cid|name"})});assert.equal(value.db,"private.db");assert.equal(value.database.logical_backend_count,1);assert.equal(value.database.listener_count,0);assert.equal(value.database.ready_bool,false);});
test("package core acceptance command has no caller arguments",()=>{const pkg=JSON.parse(fs.readFileSync(path.join(__dirname,"..","package.json"),"utf8"));assert.equal(pkg.scripts["acceptance:core"],"node scripts/core-e2e-acceptance.cjs");});
test("SQLite active meeting contract accepts only canonical in_meeting",()=>{const db=path.join(fs.mkdtempSync(path.join(os.tmpdir(),"core-state-")),"state.db");assert.equal(spawnSync("sqlite3",[db,"CREATE TABLE meetings(state TEXT); INSERT INTO meetings VALUES ('in_meeting'),('in_progress'),('ended');"]).status,0);assert.equal(activeMeetings(db),1);});
test("five-field manifest writer verifies all resources and rejects a missing resource",()=>{const f=installedFixture(),manifest=path.join(path.dirname(f.manifest),"release.json");writeInstalledReleaseManifest({appPath:f.app,manifestPath:manifest});assert.deepEqual(verifyInstalledReleaseManifest({appPath:f.app,manifestPath:manifest}),{resource_count:3,hash_match:true});fs.rmSync(f.backend);assert.throws(()=>verifyInstalledReleaseManifest({appPath:f.app,manifestPath:manifest}),/resource_missing/);});
test("database readiness retries delayed backend and accepts one meetings schema",async()=>{let clock=0,attempt=0;const ready=processReport({logical_backend_count:1,supervisor_count:1,runtime_child_count:1,listener_count:1,process_tree_pid_count:4,backend_pid_count:1});const value=await waitForMeetingDb(731,{now:()=>clock,delay:async()=>{clock+=200;},timeout:1000,inspect:()=>++attempt<3?{db:null,error_code:null,database:{candidate_count:0,ready_bool:false}}:{db:"private.db",error_code:null,database:{candidate_count:1,...ready,ready_bool:true}}});assert.equal(value.db,"private.db");assert.deepEqual(value.database,{candidate_count:1,...ready,ready_bool:true,poll_count:3});});
test("database readiness keeps polling when the database opens before the listener",async()=>{let clock=0,attempt=0;const waiting=processReport({logical_backend_count:1,supervisor_count:1,runtime_child_count:1,listener_count:0,process_tree_pid_count:4,backend_pid_count:1}),ready={...waiting,listener_count:1,ready_bool:true};const value=await waitForMeetingDb(731,{now:()=>clock,delay:async()=>{clock+=200;},timeout:1000,inspect:()=>{attempt+=1;return {db:"private.db",error_code:null,database:{candidate_count:1,...(attempt<3?waiting:ready)}};}});assert.equal(value.db,"private.db");assert.equal(value.database.listener_count,1);assert.equal(value.database.ready_bool,true);assert.equal(value.database.poll_count,3);});
test("database readiness timeout writes one safe report",async()=>{const f=installedFixture(),reportPath=path.join(path.dirname(f.manifest),"report.json");let clock=0;const connection={socket:{close:()=>{}},evaluate:async()=>s(0),enableStartNetworkDiagnostics:async()=>startNetworkAggregate()};const {runtime}=lifecycle({waitForRendererReady:async()=>({connection,readiness:readiness(1,true,true,1)})});const result=await run({app:f.app,sha256:f.actual,report:reportPath,runtime,databaseRuntime:{now:()=>clock,delay:async()=>{clock+=200;},timeout:400,inspect:()=>({db:null,error_code:null,database:{candidate_count:0,ready_bool:false}})}});assert.equal(result.error_code,"database_missing");assert.deepEqual(result.database,{candidate_count:0,...processReport(),ready_bool:false,poll_count:2});assert.equal(JSON.parse(fs.readFileSync(reportPath)).error_code,"database_missing");});
test("database readiness rejects more than one meetings schema",async()=>{await assert.rejects(()=>waitForMeetingDb(731,{inspect:()=>({db:null,error_code:"database_ambiguous",database:{candidate_count:2,...processReport({process_tree_pid_count:4}),ready_bool:false}})}),(error)=>error.code==="database_ambiguous"&&!String(error.message).includes("private"));});
test("database discovery is never called before renderer readiness",async()=>{const f=installedFixture();let discovered=false;const {runtime}=lifecycle({waitForRendererReady:async()=>{const error=new Error("renderer_ready_timeout");error.code="renderer_ready_timeout";throw error;}});const result=await run({app:f.app,sha256:f.actual,runtime,databaseRuntime:{inspect:()=>{discovered=true;return {db:null,error_code:null,database:{candidate_count:0,backend_pid_count:0,ready_bool:false}}}}});assert.equal(result.error_code,"renderer_ready_timeout");assert.equal(discovered,false);});
