"""Model runtime 的稳定、无秘密错误语义。"""

from __future__ import annotations

from typing import Final

MODEL_CONFIG_INVALID: Final = "MODEL_CONFIG_INVALID"
MODEL_CONFIG_HASH_MISMATCH: Final = "MODEL_CONFIG_HASH_MISMATCH"
MODEL_ENDPOINT_MISSING: Final = "MODEL_ENDPOINT_MISSING"
MODEL_ENDPOINT_INVALID: Final = "MODEL_ENDPOINT_INVALID"
MODEL_ENDPOINT_CONFLICT: Final = "MODEL_ENDPOINT_CONFLICT"
MODEL_MODEL_MISSING: Final = "MODEL_MODEL_MISSING"
MODEL_MODEL_CONFLICT: Final = "MODEL_MODEL_CONFLICT"
MODEL_AUTH_MISSING: Final = "MODEL_AUTH_MISSING"
MODEL_AUTH_INVALID: Final = "MODEL_AUTH_INVALID"
MODEL_CAPABILITY_MISSING: Final = "MODEL_CAPABILITY_MISSING"
MODEL_CAPABILITY_CONFLICT: Final = "MODEL_CAPABILITY_CONFLICT"
MODEL_ROUTE_CONFLICT: Final = "MODEL_ROUTE_CONFLICT"
MODEL_FALLBACK_INVALID: Final = "MODEL_FALLBACK_INVALID"
MODEL_CONFIG_STALE_REVISION: Final = "MODEL_CONFIG_STALE_REVISION"
MODEL_REQUEST_IDENTITY_MISMATCH: Final = "MODEL_REQUEST_IDENTITY_MISMATCH"
MODEL_CONFIG_NOT_FOUND: Final = "MODEL_CONFIG_NOT_FOUND"
MODEL_CONFIG_STORAGE_INVALID: Final = "MODEL_CONFIG_STORAGE_INVALID"
MODEL_CONFIG_REVISION_CONFLICT: Final = "MODEL_CONFIG_REVISION_CONFLICT"
MODEL_TASK_ALREADY_PINNED: Final = "MODEL_TASK_ALREADY_PINNED"
MODEL_TASK_NOT_PINNED: Final = "MODEL_TASK_NOT_PINNED"
MODEL_CREDENTIAL_HANDLE_INVALID: Final = "MODEL_CREDENTIAL_HANDLE_INVALID"
MODEL_CREDENTIAL_UNAVAILABLE: Final = "MODEL_CREDENTIAL_UNAVAILABLE"
MODEL_CAPABILITY_UNSUPPORTED: Final = "MODEL_CAPABILITY_UNSUPPORTED"
MODEL_HEALTH_PROBE_FAILED: Final = "MODEL_HEALTH_PROBE_FAILED"
MODEL_FALLBACK_EXHAUSTED: Final = "MODEL_FALLBACK_EXHAUSTED"


class ModelRuntimeError(Exception):
    """所有错误的可审计外壳；message 只允许安全的固定文本。"""

    def __init__(self, code: str, *, field: str | None = None) -> None:
        self.code = code
        self.field = field
        # 不接收或拼接任何原始输入，尤其是 credential/token/endpoint 值。
        message = code if field is None else f"{code}: {field}"
        super().__init__(message)


class ModelRuntimeConfigError(ModelRuntimeError):
    """配置缺失、格式错误或内部字段冲突。"""


class ModelRuntimeStaleRevisionError(ModelRuntimeError):
    """调用方使用了不是当前绑定 revision 的配置。"""


class ModelRuntimeRequestIdentityError(ModelRuntimeError):
    """请求 identity 与 snapshot 不匹配。"""


__all__ = [
    "MODEL_AUTH_INVALID",
    "MODEL_AUTH_MISSING",
    "MODEL_CAPABILITY_CONFLICT",
    "MODEL_CAPABILITY_MISSING",
    "MODEL_CAPABILITY_UNSUPPORTED",
    "MODEL_CONFIG_HASH_MISMATCH",
    "MODEL_CONFIG_INVALID",
    "MODEL_CONFIG_NOT_FOUND",
    "MODEL_CONFIG_REVISION_CONFLICT",
    "MODEL_CONFIG_STALE_REVISION",
    "MODEL_CONFIG_STORAGE_INVALID",
    "MODEL_CREDENTIAL_HANDLE_INVALID",
    "MODEL_CREDENTIAL_UNAVAILABLE",
    "MODEL_ENDPOINT_CONFLICT",
    "MODEL_ENDPOINT_INVALID",
    "MODEL_ENDPOINT_MISSING",
    "MODEL_FALLBACK_EXHAUSTED",
    "MODEL_FALLBACK_INVALID",
    "MODEL_HEALTH_PROBE_FAILED",
    "MODEL_MODEL_CONFLICT",
    "MODEL_MODEL_MISSING",
    "MODEL_REQUEST_IDENTITY_MISMATCH",
    "MODEL_ROUTE_CONFLICT",
    "MODEL_TASK_ALREADY_PINNED",
    "MODEL_TASK_NOT_PINNED",
    "ModelRuntimeConfigError",
    "ModelRuntimeError",
    "ModelRuntimeRequestIdentityError",
    "ModelRuntimeStaleRevisionError",
]
